-- Verified working ATS boards (probed live 2026-06-17).
-- Greenhouse 'notion' was wrong (Notion uses Ashby) — deactivate it.
update ats_source set active = false where provider = 'greenhouse' and board_token = 'notion';

insert into ats_source (provider, board_token, company, active) values
    ('greenhouse', 'phonepe', 'PhonePe', true),
    ('greenhouse', 'groww', 'Groww', true),
    ('greenhouse', 'postman', 'Postman', true),
    ('lever', 'cred', 'CRED', true),
    ('greenhouse', 'druva', 'Druva', true),
    ('greenhouse', 'highradius', 'HighRadius', true),
    ('greenhouse', 'slice', 'Slice', true),
    ('lever', 'meesho', 'Meesho', true),
    ('lever', 'mindtickle', 'Mindtickle', true),
    ('ashby', 'navi', 'Navi', true),
    ('greenhouse', 'gitlab', 'GitLab', true),
    ('greenhouse', 'stripe', 'Stripe', true),
    ('greenhouse', 'robinhood', 'Robinhood', true),
    ('greenhouse', 'dropbox', 'Dropbox', true),
    ('greenhouse', 'coinbase', 'Coinbase', true),
    ('greenhouse', 'instacart', 'Instacart', true),
    ('greenhouse', 'airbnb', 'Airbnb', true),
    ('lever', 'zeta', 'Zeta', true),
    ('greenhouse', 'lyft', 'Lyft', true),
    ('greenhouse', 'databricks', 'Databricks', true),
    ('greenhouse', 'pinterest', 'Pinterest', true),
    ('greenhouse', 'brex', 'Brex', true),
    ('greenhouse', 'reddit', 'Reddit', true),
    ('greenhouse', 'figma', 'Figma', true),
    ('greenhouse', 'discord', 'Discord', true),
    ('greenhouse', 'datadog', 'Datadog', true),
    ('greenhouse', 'asana', 'Asana', true),
    ('ashby', 'plaid', 'Plaid', true),
    ('greenhouse', 'gusto', 'Gusto', true),
    ('greenhouse', 'samsara', 'Samsara', true),
    ('greenhouse', 'twilio', 'Twilio', true),
    ('greenhouse', 'okta', 'Okta', true),
    ('greenhouse', 'cloudflare', 'Cloudflare', true),
    ('greenhouse', 'elastic', 'Elastic', true),
    ('greenhouse', 'faire', 'Faire', true),
    ('ashby', 'ramp', 'Ramp', true),
    ('greenhouse', 'affirm', 'Affirm', true),
    ('greenhouse', 'anthropic', 'Anthropic', true),
    ('greenhouse', 'vercel', 'Vercel', true),
    ('greenhouse', 'mongodb', 'MongoDB', true),
    ('greenhouse', 'mixpanel', 'Mixpanel', true),
    ('greenhouse', 'newrelic', 'New Relic', true),
    ('greenhouse', 'amplitude', 'Amplitude', true),
    ('greenhouse', 'scaleai', 'Scale AI', true),
    ('ashby', 'confluent', 'Confluent', true),
    ('ashby', 'cohere', 'Cohere', true),
    ('ashby', 'posthog', 'PostHog', true),
    ('greenhouse', 'planetscale', 'PlanetScale', true),
    ('ashby', 'linear', 'Linear', true),
    ('ashby', 'notion', 'Notion', true),
    ('ashby', 'sentry', 'Sentry', true),
    ('ashby', 'render', 'Render', true),
    ('greenhouse', 'nubank', 'Nubank', true),
    ('ashby', 'supabase', 'Supabase', true),
    ('ashby', 'airbyte', 'Airbyte', true),
    ('ashby', 'temporal', 'Temporal', true),
    ('ashby', 'snowflake', 'Snowflake', true),
    ('ashby', 'replit', 'Replit', true),
    ('ashby', 'openai', 'OpenAI', true)
on conflict (provider, board_token)
    do update set active = excluded.active, company = excluded.company;
